### ISSUE TITLE
Context menu not displaying properly

### ISSUE THREAD

**Issue by danesparza** [jamesmkwan/ChromeToPaper#1]
The right-click context menu is not displaying at all.  Saving using the browser button appears to work.

**Comment by jamesmkwan** [comment]
Have you enabled it in the options page? The new version requires has an option to add/remove it. If already enabled, try disabling it then re-enabling it. After that, close the browser and reopen it.

**Comment by danesparza** [comment]
I have.  I also turned it off and on again and restarted my browser.  Still no dice.  I even disabled all other extensions (thinking it might be a conflict).  No dice.

**Comment by jamesmkwan** [comment]
Did it previously work for you in version 2.4?

**Comment by danesparza** [comment]
Not sure of the version number, but it worked as recently as yesterday for me.  (When did this version get released?)

**Comment by jamesmkwan** [comment]
Version 2.5 (current) was just released today. Could you please try disabling and re-enabling the ChromeToPaper extension? Also, what links are you trying this on?

**Comment by danesparza** [comment]
I'm trying this on text an links on wsj.com, but other links don't work either.  Doesn't seem to matter where I try to use it.  I tried disabling/re-enabling right now.  I also tried uninstalling / re-installing.  No dice.

**Comment by jamesmkwan** [comment]
That's odd. It's working for me. Could you let me know what browser version and operating system that you're using?

**Comment by danesparza** [comment]
Windows 7 
Chrome 10.0.648.119 beta

**Comment by sgausman** [comment]
I'm having the same issue.

Windows XP SP3
Chrome 10.0.648.114 beta

**Comment by danesparza** [comment]
Having the same issue in Windows 7 / Chrome 9.0.597.98

**Comment by jamesmkwan** [comment]
I've created a new version.

Version 2.5.3: Update Instructions
1. Right-click the ChromeToPaper button and click Manage Extensions
2. Click the + next to developer mode so that it expands a row of buttons
3. In the row of buttons, click Update extensions now
4. Verify that the version number next to ChromeToPaper has changed

Let me know if it solves your problem!

**Comment by danesparza** [comment]
Looks like it works beautifully now.  Thanks!  (Tested on Windows 7 / Chrome 10.0.648.119 beta )

**Comment by jamesmkwan** [comment]
Sure thing. In case you're wondering what happened:

The old ChromeToPaper option for the context menu took effect on restart. Apparently, it was not registering on some people's computers. The new ChromeToPaper to immediately updates the context menu after someone changes the setting.
