### ISSUE TITLE
Chrome style icon

### ISSUE THREAD

**Issue by joshje** [jamesmkwan/ChromeToPaper#11]
This icon should hopefully look identical to the default icons for Google Chrome. Feel free to use it, I don't need any acknowledgement.

![Instapaper Icon](http://f.cl.ly/items/0x390R013a2o2F471E33/instapaper-chrome.png)

http://cl.ly/image/0y1b0y2w3039

**Comment by joshje** [comment]
I've taken a look at other icons, and realised you use 16, 19, 48 and 128 sized assets. I've generated all 4 scales, so that the 1px white drop shadow looks sharp at each size.

http://cl.ly/1i0y3K0I472f

**Comment by jamesmkwan** [comment]
Thanks! I'll try to add them soon.

**Comment by jamesmkwan** [comment]
Just added it. If you update the extension to the latest version, you should see it under Appearance. If it doesn't look like how you envisioned it, feel free to modify the images and send it to me.

How to update immediately: https://github.com/jamesmkwan/ChromeToPaper/wiki/Update-ChromeToPaper
