### ISSUE TITLE
Instpaper and Chrome to Paper the same login?

### ISSUE THREAD

**Issue by ghost** [jamesmkwan/ChromeToPaper#12]
I can log in to Instapaper but the same login won't work in ChrometoPaper.  Whats the story.

**Comment by jamesmkwan** [comment]
The login you provide to ChromeToPaper should be the same as instapaper.com. I just tested it and it seems to work fine for me.

Could you provide more information?

Is this your first time using the extension? If not, did it work before?

What kind of error message do you get? Could you let me know what the Javascript Console (Menu -> More Tools -> JavaScript Console) says? If shown, make sure to blank out your login password before posting the console output.
