### ISSUE TITLE
Chrome Default theme icons

### ISSUE THREAD

**Issue by andregriffin** [jamesmkwan/ChromeToPaper#6]
http://dl.dropbox.com/u/57818/instapaper_icons.zip

Created by Andre Griffin

**Comment by jamesmkwan** [comment]
Thanks for your submission.
1. Do you have a name for your icon? I would call it "transparent" but it's already taken.
2. Your icon is a bit out of proportion compared to the standard icon. This is fine, but I wanted to warn you in case it is not what you intended. In the picture, the left is the "transparent" icon and the right is your icon: http://ge.tt/7Fthoq9/Untitled.png
3. I'm assuming that you want "Created by Andre Griffin" in the description. Is this correct?

**Comment by andregriffin** [comment]
Well, it's intended to match the style of the buttons in the default chrome theme, so maybe it can be called Chrome Theme or something. Whatever you choose is fine.

I realize that the "I" is a bit different, It Instapaper seems to only have "Georgia" font as a requirement for their logo, and that's what font is used here. 

It's not necessary to credit me really, but if you'd like to, you can use "Created by andregriffin.com"

**Comment by jamesmkwan** [comment]
I don't want to call it Chrome since I might run into some issues from Google. Do you have any other options?

AFAIK, Instapaper uses Times in its logo. They use Georgia for the website, though, since it is more widely available.

I had assumed that you wanted that as your credit since underneath the link you had stated that. So you want "andregriffin.com" instead of "Andre Griffin"?

**Comment by andregriffin** [comment]
http://dl.dropbox.com/u/57818/instapaper-icons.zip

Here is a version using Times. You're right, it looks better.

Call it Minimal, or something like that is fine.

Credit: "andregriffin.com"

Hope it works out!

**Comment by jamesmkwan** [comment]
Thanks for working this out with me. Minimalist is a good name, and the icon looks quite nice next to the Chrome wrench. I've added the icon into the source code, and the icon should be available next time I push an update.
