### ISSUE TITLE
Keyboard shortcuts don't work

### ISSUE THREAD

**Issue by craigarn** [jamesmkwan/ChromeToPaper#7]
I have Chrome 12.0.742.122 running on OS X Snow Leopard (10.6.8) and pushing Alt/Option+R (the shortcut I assigned for adding a page to Instapaper) and when pushing Alt/Opt+R, I get an HTML5 notification saying that "The server refused to process the request." When I click on the button in the toolbar, it sends the page to Instapaper just fine. Why would it do this?

ChromeToPaper 2.5.4.4
CTP Keyboard Shortcuts 1.4

**Comment by jamesmkwan** [comment]
Hello,

Thank you for taking the time to submit a bug report. I have a few questions that would help me find the issue:
1. Does this happen to most webpages, or just this one? (If it is just this one, what is its URL)
2. Does it work if you try another shortcut?

Thanks,
James

**Comment by craigarn** [comment]
This happens on all webpages that I've tried so far (facebook, youtube, lifehacker and several others)

Another shortcut makes no difference. 

This is the error I get: http://d.cpx.me/TX6O

Also, I went and looked at the background page that the keyboard shortcut extension leaves open, and inspected the resources. These errors look kind of API-like: http://d.cpx.me/arfL

**Comment by jamesmkwan** [comment]
Hello,

Thanks for the very helpful information. I have modified the code for both of the extensions (it seems that I accidentally deleted some important code).

Follow these steps:
1. Update both extensions (see https://github.com/jamesmkwan/ChromeToPaper/wiki/Update-ChromeToPaper)
2. Verify that the version numbers have changed, and restart Google Chrome. 

Please let me know if it solves the issue.

Best,
James

**Comment by craigarn** [comment]
It does.

Thanks.
