### ISSUE TITLE
Bug report: Chinese characters in page title get garbled 

### ISSUE THREAD

**Issue by akfish** [jamesmkwan/ChromeToPaper#8]
**Description:**
When adding a web page containing Chinese characters (possibly any non-English characters) in its title, the title in Instapaper's list gets garbled.

**Steps for reproducing this issue:**
1. Open any web page with Chinese characters in the title. (Sample: http://www.engadget.com/2012/02/23/nvidia-officially-brands-tegra-3s-five-core-quad-core-architect/)
2. Click "ChromeToPaper"
3. Check the newly added item's title in instapaper

Expected result:
`NVIDIA 官方正式将 Tegra 3 四核架构的第五核心技术命名为「4-PLUS-1」`

Current result: 
`NVIDIA å®æ¹æ­£å¼å° Tegra 3 åæ ¸æ¶æçç¬¬äºæ ¸å¿ææ¯å½åä¸ºã4-PLUS-1ã`

**Suggestions on how to fix this issue:**

After I tested and compared a few other similar applications, it is clear that this issue is caused by Instapapper's incapability of filling title containing non-English characters correctly. Providing the title explicitly will fix this issue.

**Comment by dmaslakov** [comment]
Similar issue with Russian.

**Comment by jamesmkwan** [comment]
Should be fixed in V2.6.1.2. Sorry about the wait.

Chrome will automatically update to this version or you can force an update immediately:
https://github.com/jamesmkwan/ChromeToPaper/wiki/Update-ChromeToPaper
